"""
Threat data models
"""

from datetime import datetime
from typing import Optional, Dict, Any, List
from pydantic import BaseModel, Field
from enum import Enum


class ThreatType(str, Enum):
    """Threat classification types"""
    MALWARE = "malware"
    EXPLOIT = "exploit"
    PHISHING = "phishing"
    DDoS = "ddos"
    DATA_EXFILTRATION = "data_exfiltration"
    UNAUTHORIZED_ACCESS = "unauthorized_access"
    AI_POWERED_ATTACK = "ai_powered_attack"
    AUTONOMOUS_HACKING = "autonomous_hacking"
    UNKNOWN = "unknown"


class ThreatSeverity(str, Enum):
    """Threat severity levels"""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class TelemetryEvent(BaseModel):
    """System telemetry event"""
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    source_ip: str
    destination_ip: Optional[str] = None
    protocol: Optional[str] = None
    port: Optional[int] = None
    bytes_sent: Optional[int] = None
    bytes_received: Optional[int] = None
    user_agent: Optional[str] = None
    endpoint: Optional[str] = None
    status_code: Optional[int] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class CodeSample(BaseModel):
    """Code sample for analysis"""
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    source: str  # e.g., "github", "pastebin", "darkweb"
    code_content: str
    language: Optional[str] = None
    file_name: Optional[str] = None
    hash: Optional[str] = None  # SHA256 hash
    metadata: Dict[str, Any] = Field(default_factory=dict)
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class DarkWebFeed(BaseModel):
    """Dark web data feed"""
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    source: str
    content: str
    url: Optional[str] = None
    author: Optional[str] = None
    keywords: List[str] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class ThreatEvent(BaseModel):
    """Base threat event"""
    event_id: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    threat_type: ThreatType
    severity: ThreatSeverity
    source: str  # "telemetry", "code_sample", "darkweb"
    confidence_score: float = Field(ge=0.0, le=1.0)
    description: str
    raw_data: Dict[str, Any] = Field(default_factory=dict)
    metadata: Dict[str, Any] = Field(default_factory=dict)
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class ThreatProfile(BaseModel):
    """Comprehensive threat profile generated by AI"""
    profile_id: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    threat_type: ThreatType
    severity: ThreatSeverity
    confidence_score: float = Field(ge=0.0, le=1.0)
    
    # AI Analysis Results
    ai_analysis: Dict[str, Any] = Field(default_factory=dict)
    behavioral_patterns: List[str] = Field(default_factory=list)
    indicators_of_compromise: List[str] = Field(default_factory=list)
    autonomous_system_indicators: List[str] = Field(default_factory=list)
    
    # Source Data
    source_events: List[str] = Field(default_factory=list)  # Event IDs
    related_threats: List[str] = Field(default_factory=list)  # Related profile IDs
    
    # MITRE ATT&CK Mapping
    mitre_tactics: List[str] = Field(default_factory=list)
    mitre_techniques: List[str] = Field(default_factory=list)
    
    metadata: Dict[str, Any] = Field(default_factory=dict)
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


